-- Photo storage bucket for the centralized library + per-project photos.
-- Run AFTER 001_init.sql.

insert into storage.buckets (id, name, public)
values ('photos', 'photos', false)
on conflict (id) do nothing;

-- Authenticated users can upload to the photos bucket.
drop policy if exists "auth uploads photos" on storage.objects;
create policy "auth uploads photos" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'photos');

-- Authenticated users can read photos. Public quote pages use signed URLs
-- generated by the server, so no public anon access is needed.
drop policy if exists "auth reads photos" on storage.objects;
create policy "auth reads photos" on storage.objects
  for select to authenticated
  using (bucket_id = 'photos');

-- Admin/office can delete; crew cannot.
drop policy if exists "admin office deletes photos" on storage.objects;
create policy "admin office deletes photos" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'photos'
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'office')
    )
  );
