-- Rose Concrete — project-scoped photo library
--
-- Single source of truth for every photo on every project. The marketing
-- site, social-post drafter, and quote-PDF embedder all pull from here.
-- No separate "media library" table — photos live on the project they
-- came from, and downstream consumers filter by the existing
-- service_type / city / completion-status signals via JOIN.
--
-- Backfill at the bottom: any projects created before service_type was
-- mandatory get their service_type populated from the lead that
-- spawned them. Required because the marketing helpers filter by
-- service_type and a NULL would silently exclude the project.
--
-- Run in the Supabase SQL editor, after 032.

-- ─── Storage bucket ──────────────────────────────────────────────────────

-- The `project-media` bucket is PUBLIC-READ so the marketing site can
-- serve <img src="..."> directly. Anything Ronnie wants to keep private
-- (signed contracts, permits, customer ID scans) belongs in the existing
-- private `photos` bucket from migration 003 — different bucket, different
-- access model.
insert into storage.buckets (id, name, public, file_size_limit)
values ('project-media', 'project-media', true, 10 * 1024 * 1024)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit;

-- Public read — anyone can fetch a project-media object by URL.
drop policy if exists "public reads project-media" on storage.objects;
create policy "public reads project-media" on storage.objects
  for select using (bucket_id = 'project-media');

-- Admin / office / crew can upload. Tightening to "only the crew assigned
-- to this specific project" is a future RLS refinement — for MVP, anyone
-- in the operations app can attach a photo to any project.
drop policy if exists "team uploads project-media" on storage.objects;
create policy "team uploads project-media" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'project-media'
    and exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role in ('admin', 'office', 'crew')
    )
  );

-- Admin / office can delete. Crew can upload but not delete (matches the
-- existing photos-bucket pattern from migration 003).
drop policy if exists "admin office deletes project-media" on storage.objects;
create policy "admin office deletes project-media" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'project-media'
    and public.is_office_or_admin()
  );

-- Admin / office can update (rename, replace). Same gate as delete.
drop policy if exists "admin office updates project-media" on storage.objects;
create policy "admin office updates project-media" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'project-media'
    and public.is_office_or_admin()
  );

-- ─── project_media table ─────────────────────────────────────────────────

do $$ begin
  create type project_media_phase as enum (
    'before',
    'during',
    'after',
    'detail',
    'reference'
  );
exception when duplicate_object then null; end $$;

create table if not exists public.project_media (
  id                     uuid primary key default uuid_generate_v4(),
  project_id             uuid not null references public.projects(id) on delete cascade,
  -- Storage layout: project-media/projects/<project_id>/<uuid>.<ext>
  storage_path           text not null,
  -- Cached public URL — denormalized so the marketing site doesn't have
  -- to call storage.from('...').getPublicUrl() in the hot read path.
  public_url             text not null,
  original_filename      text,
  mime_type              text,
  width                  int,
  height                 int,
  -- AI-generated by lib/project-media/alt-text.ts on upload (best-effort).
  -- Manually editable. Falls back to a sensible default if generation fails.
  alt_text               text,
  phase                  project_media_phase not null default 'after',
  -- Default true — most photos go on the website. Uncheck for jobs where
  -- the customer asked for privacy or the photo isn't presentable.
  is_marketing_eligible  boolean not null default true,
  -- Manually-promoted hero shots. Drives <RecentProjects /> + hero rotation.
  is_hero                boolean not null default false,
  sort_order             int not null default 0,
  -- Caption is Phase-2 social-post copy. Optional, manually edited.
  caption                text,
  uploaded_by            uuid references public.profiles(id) on delete set null,
  created_at             timestamptz not null default now()
);

create index if not exists project_media_project_idx
  on public.project_media (project_id);
create index if not exists project_media_phase_idx
  on public.project_media (phase);
create index if not exists project_media_marketing_idx
  on public.project_media (is_marketing_eligible)
  where is_marketing_eligible = true;
create index if not exists project_media_hero_idx
  on public.project_media (is_hero)
  where is_hero = true;
create index if not exists project_media_sort_idx
  on public.project_media (project_id, sort_order, created_at);

alter table public.project_media enable row level security;

-- Admin / office full read+write. Crew can read all photos and create
-- new ones (so they can upload from the field) but can't edit existing
-- rows or delete (matches the storage policies above).
create policy "admin office full access project_media"
  on public.project_media for all
  using (public.is_office_or_admin());

create policy "crew read project_media"
  on public.project_media for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'office', 'crew')
    )
  );

create policy "crew insert project_media"
  on public.project_media for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role in ('admin', 'office', 'crew')
    )
  );

-- ─── Helper view: project_media joined with project + client metadata ───
--
-- The marketing helpers in lib/marketing/project-photos.ts filter by
-- service_type and city, both of which live on `projects` and
-- `clients` respectively. This view does the join once so callers can
-- query a flat row.
--
-- Kept as `marketing_project_media` (not `project_media_with_meta`) to
-- signal that it's the read-side projection used by marketing — the raw
-- table stays the write target.

create or replace view public.marketing_project_media as
select
  m.id,
  m.project_id,
  m.storage_path,
  m.public_url,
  m.original_filename,
  m.mime_type,
  m.width,
  m.height,
  m.alt_text,
  m.phase,
  m.is_marketing_eligible,
  m.is_hero,
  m.sort_order,
  m.caption,
  m.created_at,
  p.service_type,
  p.status        as project_status,
  p.name          as project_name,
  c.id            as client_id,
  c.city          as client_city,
  c.postal_code   as client_postal_code
from public.project_media m
join public.projects p on p.id = m.project_id
left join public.clients c on c.id = p.client_id;

grant select on public.marketing_project_media to authenticated;
-- Public role for the marketing site (anonymous visitors). The view
-- inherits the underlying table's RLS — but the marketing helpers use
-- the service-role client anyway, so this `grant` is for future direct
-- anon reads (e.g. an Edge Function that pre-generates a static image
-- gallery).
grant select on public.marketing_project_media to anon;

-- ─── Backfill: projects.service_type from the lead that spawned them ────
--
-- Most projects are created via lib/leads.ts createLead() which sets
-- service_type from the intake. But projects created via the legacy
-- /dashboard/projects/new form before service_type was wired, or via
-- a Jobber import where the type wasn't mapped, can be NULL. Marketing
-- queries filter on service_type — a NULL silently excludes the project,
-- which we don't want.
--
-- Strategy: for any project with service_type IS NULL, look up the most
-- recent lead pointing at that project and copy its service_type over.
-- Idempotent — safe to re-run.

update public.projects p
set service_type = sub.service_type
from (
  select distinct on (l.project_id)
    l.project_id,
    l.service_type
  from public.leads l
  where l.project_id is not null
    and l.service_type is not null
  order by l.project_id, l.captured_at desc
) sub
where p.id = sub.project_id
  and p.service_type is null;
